import { useState } from 'react';
import { Check, Download, FileText, MessageCircle, Send, Wallet } from 'lucide-react';
import type { Invoice, Task, Thread } from './types';

export default function ClientPortal({ page, setPage, tasks, setTasks, invoices, setInvoices, threads, setThreads, showToast }: { page: string; setPage: (page: string) => void; tasks: Task[]; setTasks: React.Dispatch<React.SetStateAction<Task[]>>; invoices: Invoice[]; setInvoices: React.Dispatch<React.SetStateAction<Invoice[]>>; threads: Thread[]; setThreads: React.Dispatch<React.SetStateAction<Thread[]>>; showToast: (message: string) => void }) {
  if (page === 'tasks') return <ClientTasks tasks={tasks} setTasks={setTasks} />;
  if (page === 'invoices') return <ClientInvoices invoices={invoices} setInvoices={setInvoices} showToast={showToast} />;
  if (page === 'messages' || page === 'whatsapp') return <ClientMessages threads={threads} setThreads={setThreads} showToast={showToast} />;
  if (page === 'projects') return <ClientProjects />;
  if (page === 'announcements') return <Announcements />;
  return <ClientOverview setPage={setPage} tasks={tasks} invoices={invoices} />;
}
function ClientOverview({ setPage, tasks, invoices }: { setPage: (page: string) => void; tasks: Task[]; invoices: Invoice[] }) { return <><div className="portal-banner"><div><p className="eyebrow" style={{ color: '#91c9aa' }}>Agency OS / Client space</p><h2>Welcome back, Olivia.</h2><p>Your team has a few updates waiting for you.</p></div><div className="avatar portal-avatar">OS</div></div><div className="portal-grid"><div className="panel"><div className="panel-head"><div><h3>Northstar rebrand</h3><span className="muted">Active project · Due Sep 12</span></div><span className="pill green">On track</span></div><div className="portal-stat"><strong>68% complete</strong><span>Phase 3 of 4</span></div><div className="progress"><span style={{ width: '68%' }} /></div><button className="portal-link" onClick={() => setPage('projects')}>View project details →</button></div><div className="panel"><div className="panel-head"><h3>Next invoice</h3><Wallet size={17} color="#0f7a5c" /></div><div className="portal-invoice"><strong>{invoices[0]?.number || 'No invoices'}</strong><b>₹{invoices[0]?.total.toLocaleString('en-IN') || '0'}</b><span>Due {invoices[0]?.due || '—'}</span></div><button className="portal-link" onClick={() => setPage('invoices')}>View all invoices →</button></div></div><div className="panel portal-tasks"><div className="panel-head"><div><h3>Open tasks</h3><span className="muted">Visible to you</span></div><button className="portal-link" onClick={() => setPage('tasks')}>View all →</button></div>{tasks.filter((task) => task.status !== 'done').slice(0, 3).map((task) => <div className="task" key={task.id}><span className="check" /><div><strong>{task.title}</strong><small>{task.due} · {task.status.replace('_', ' ')}</small></div></div>)}</div></>; }
function ClientTasks({ tasks, setTasks }: { tasks: Task[]; setTasks: React.Dispatch<React.SetStateAction<Task[]>> }) { return <><ClientHead title="Tasks" description="Review the work your agency team is moving forward." /><div className="portal-task-grid">{(['todo', 'in_progress', 'review', 'done'] as Task['status'][]).map((status) => <div className="panel" key={status}><div className="panel-head"><h3>{status === 'todo' ? 'To do' : status === 'in_progress' ? 'In progress' : status[0].toUpperCase() + status.slice(1)}</h3><span className="pill">{tasks.filter((task) => task.status === status).length}</span></div>{tasks.filter((task) => task.status === status).map((task) => <div className="task" key={task.id}><button className={`check ${status === 'done' ? 'checked' : ''}`} onClick={() => setTasks((current) => current.map((item) => item.id === task.id ? { ...item, status: item.status === 'done' ? 'review' : 'done' } : item))}>{status === 'done' && <Check size={11} />}</button><div><strong>{task.title}</strong><small>{task.client} · {task.due}</small></div></div>)}</div>)}</div></>; }
function ClientInvoices({ invoices, setInvoices, showToast }: { invoices: Invoice[]; setInvoices: React.Dispatch<React.SetStateAction<Invoice[]>>; showToast: (message: string) => void }) { return <><ClientHead title="Invoices" description="Review invoices, download records, and pay securely in the demo." /><div className="section-wrap"><table className="table"><thead><tr><th>Invoice</th><th>Status</th><th>Due</th><th>Total</th><th>Actions</th></tr></thead><tbody>{invoices.map((invoice) => <tr key={invoice.id}><td><strong>{invoice.number}</strong><small>{invoice.client}</small></td><td><span className={`pill ${invoice.status === 'paid' ? 'green' : invoice.status === 'overdue' ? 'red' : 'blue'}`}>{invoice.status}</span></td><td className="muted">{invoice.due}</td><td><strong>₹{invoice.total.toLocaleString('en-IN')}</strong></td><td><div className="client-actions"><button className="secondary" onClick={() => showToast(`${invoice.number} download started`)}><Download size={14} /> Download</button>{invoice.status !== 'paid' && <button className="primary" onClick={() => { setInvoices((current) => current.map((item) => item.id === invoice.id ? { ...item, status: 'paid' } : item)); showToast(`${invoice.number} marked paid`); }}><Wallet size={14} /> Pay now</button>}</div></td></tr>)}</tbody></table></div></>; }
function ClientMessages({ threads, setThreads, showToast }: { threads: Thread[]; setThreads: React.Dispatch<React.SetStateAction<Thread[]>>; showToast: (message: string) => void }) { const [text, setText] = useState(''); const thread = threads[0]; const send = () => { if (!text.trim()) return; const message = { id: `pm${Date.now()}`, direction: 'outbound' as const, sender: 'Olivia', text: text.trim(), time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }; setThreads((current) => current.map((item, index) => index === 0 ? { ...item, preview: message.text, messages: [...item.messages, message] } : item)); setText(''); showToast('Message sent to Agency OS'); }; return <><ClientHead title="Messages" description="A direct line to your Agency OS team." /><div className="client-chat panel"><div className="client-chat-head"><div className="avatar">MC</div><div><strong>Agency OS team</strong><small><MessageCircle size={12} /> Connected via WhatsApp</small></div><span className="pill green">Active</span></div><div className="messages">{thread.messages.map((message) => <div className={`bubble ${message.direction === 'inbound' ? 'in' : 'out'}`} key={message.id}>{message.text}<time>{message.time}</time></div>)}</div><div className="composer"><input value={text} onChange={(event) => setText(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && send()} placeholder="Write to your team..." /><button className="primary" onClick={send}><Send size={14} /> Send</button></div></div></>; }
function ClientProjects() { return <><ClientHead title="Projects" description="See progress, milestones, and the next important handoff." /><div className="portal-project panel"><div className="panel-head"><div><h3>Northstar rebrand</h3><span className="muted">Active · Started Aug 01 · Due Sep 12</span></div><span className="pill green">68% complete</span></div><div className="progress"><span style={{ width: '68%' }} /></div><div className="milestones"><div className="milestone done"><span>✓</span><div><strong>Discovery and direction</strong><small>Complete · Aug 08</small></div></div><div className="milestone done"><span>✓</span><div><strong>Visual identity system</strong><small>Complete · Aug 16</small></div></div><div className="milestone current"><span>3</span><div><strong>Website concepts</strong><small>In review · Feedback requested</small></div></div><div className="milestone"><span>4</span><div><strong>Production handoff</strong><small>Up next</small></div></div></div></div></>; }
function Announcements() { return <><ClientHead title="Announcements" description="Updates and notes from your Agency OS team." /><div className="announcement-list"><article className="panel"><span className="pill green">Project update</span><h3>Your new brand system is ready to review</h3><p className="muted">We uploaded the latest round of concepts and notes. Your feedback will help us move into production.</p><small>Today · Maya Chen</small></article><article className="panel"><span className="pill blue">Agency news</span><h3>August reporting is now available</h3><p className="muted">Your performance report and campaign learnings are ready in the shared workspace.</p><small>Aug 18 · Arjun Rao</small></article></div></>; }
function ClientHead({ title, description }: { title: string; description: string }) { return <div className="page-head"><div><p className="eyebrow">Agency OS / Client space</p><h1>{title}</h1><p>{description}</p></div></div>; }
